export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

export interface Quiz {
  id: string;
  title: string;
  description: string;
  icon: string;
  questions: QuizQuestion[];
  difficulty: "facile" | "moyen" | "difficile";
}

export const quizzes: Quiz[] = [
  {
    id: "1",
    title: "Vie de Jésus",
    description: "Testez vos connaissances sur la vie de Jésus",
    icon: "✝️",
    difficulty: "moyen",
    questions: [
      {
        id: "1-1",
        question: "En quelle année Jésus est-il né?",
        options: ["4 av. J.-C.", "1 ap. J.-C.", "10 ap. J.-C.", "5 av. J.-C."],
        correctAnswer: 0,
        explanation: "Jésus est né vers 4 av. J.-C., selon les historiens.",
      },
      {
        id: "1-2",
        question: "Quel était le métier de Joseph?",
        options: ["Pêcheur", "Charpentier", "Agriculteur", "Marchand"],
        correctAnswer: 1,
        explanation: "Joseph était charpentier à Nazareth.",
      },
      {
        id: "1-3",
        question: "Combien de disciples Jésus avait-il?",
        options: ["10", "12", "15", "20"],
        correctAnswer: 1,
        explanation: "Jésus avait 12 disciples apostoliques.",
      },
      {
        id: "1-4",
        question: "Quel était le nom du traître parmi les disciples?",
        options: ["Pierre", "Jean", "Judas", "Thomas"],
        correctAnswer: 2,
        explanation: "Judas Iscariote a trahi Jésus pour 30 pièces d'argent.",
      },
      {
        id: "1-5",
        question: "Sur quelle montagne Jésus a-t-il donné le Sermon?",
        options: ["Mont Sinaï", "Mont Carmel", "Mont des Oliviers", "Mont Tabor"],
        correctAnswer: 2,
        explanation: "Le Sermon sur la Montagne a été donné sur le Mont des Oliviers.",
      },
      {
        id: "1-6",
        question: "Combien de miracles Jésus a-t-il accomplis?",
        options: ["Environ 35", "Environ 50", "Environ 30", "Environ 40"],
        correctAnswer: 0,
        explanation: "Les évangiles rapportent environ 35 miracles de Jésus.",
      },
      {
        id: "1-7",
        question: "Quel était le nom de la mère de Jésus?",
        options: ["Marie", "Élisabeth", "Anne", "Jeanne"],
        correctAnswer: 0,
        explanation: "La mère de Jésus s'appelait Marie.",
      },
      {
        id: "1-8",
        question: "À quel âge Jésus a-t-il commencé son ministère?",
        options: ["25 ans", "30 ans", "35 ans", "40 ans"],
        correctAnswer: 1,
        explanation: "Jésus avait environ 30 ans quand il a commencé son ministère.",
      },
      {
        id: "1-9",
        question: "Combien de temps le ministère de Jésus a-t-il duré?",
        options: ["1 an", "2 ans", "3 ans", "5 ans"],
        correctAnswer: 2,
        explanation: "Le ministère public de Jésus a duré environ 3 ans.",
      },
      {
        id: "1-10",
        question: "Quel jour Jésus a-t-il ressuscité?",
        options: ["Samedi", "Dimanche", "Lundi", "Vendredi"],
        correctAnswer: 1,
        explanation: "Jésus a ressuscité le dimanche, le premier jour de la semaine.",
      },
    ],
  },
  {
    id: "2",
    title: "Ancien Testament",
    description: "Explorez l'histoire de l'Ancien Testament",
    icon: "📜",
    difficulty: "moyen",
    questions: [
      {
        id: "2-1",
        question: "Qui a créé le monde selon la Genèse?",
        options: ["Les anges", "Dieu", "Les hommes", "La nature"],
        correctAnswer: 1,
        explanation: "Dieu a créé le monde en six jours.",
      },
      {
        id: "2-2",
        question: "Quel était le nom du premier homme?",
        options: ["Noé", "Abraham", "Adam", "Moïse"],
        correctAnswer: 2,
        explanation: "Adam était le premier homme créé par Dieu.",
      },
      {
        id: "2-3",
        question: "Combien de jours Dieu a-t-il pris pour créer le monde?",
        options: ["5 jours", "6 jours", "7 jours", "8 jours"],
        correctAnswer: 1,
        explanation: "Dieu a créé le monde en 6 jours et s'est reposé le 7e jour.",
      },
      {
        id: "2-4",
        question: "Quel était le nom de la première femme?",
        options: ["Ève", "Sarah", "Rébecca", "Léa"],
        correctAnswer: 0,
        explanation: "Ève était la première femme, créée à partir de la côte d'Adam.",
      },
      {
        id: "2-5",
        question: "Combien de fils avait Noé?",
        options: ["2 fils", "3 fils", "4 fils", "5 fils"],
        correctAnswer: 1,
        explanation: "Noé avait 3 fils: Sem, Cham et Japhet.",
      },
      {
        id: "2-6",
        question: "Qui a reçu les Dix Commandements?",
        options: ["Abraham", "Noé", "Moïse", "David"],
        correctAnswer: 2,
        explanation: "Moïse a reçu les Dix Commandements sur le Mont Sinaï.",
      },
      {
        id: "2-7",
        question: "Combien de plaies Dieu a-t-il envoyées en Égypte?",
        options: ["7 plaies", "9 plaies", "10 plaies", "12 plaies"],
        correctAnswer: 2,
        explanation: "Dieu a envoyé 10 plaies en Égypte.",
      },
      {
        id: "2-8",
        question: "Quel prophète a prédit la venue du Messie?",
        options: ["Jérémie", "Ésaïe", "Ézéchiel", "Daniel"],
        correctAnswer: 1,
        explanation: "Ésaïe a prophétisé la venue du Messie.",
      },
      {
        id: "2-9",
        question: "Qui était le roi le plus sage d'Israël?",
        options: ["David", "Salomon", "Saül", "Josias"],
        correctAnswer: 1,
        explanation: "Salomon était le roi le plus sage d'Israël.",
      },
      {
        id: "2-10",
        question: "Combien de livres contient l'Ancien Testament?",
        options: ["37 livres", "39 livres", "41 livres", "43 livres"],
        correctAnswer: 1,
        explanation: "L'Ancien Testament contient 39 livres.",
      },
    ],
  },
  {
    id: "3",
    title: "Prophètes",
    description: "Testez vos connaissances sur les prophètes",
    icon: "🔮",
    difficulty: "difficile",
    questions: [
      {
        id: "3-1",
        question: "Quel prophète a été jeté dans la fosse aux lions?",
        options: ["Jérémie", "Daniel", "Ézéchiel", "Osée"],
        correctAnswer: 1,
        explanation: "Daniel a été jeté dans la fosse aux lions mais Dieu l'a sauvé.",
      },
      {
        id: "3-2",
        question: "Quel prophète a été avalé par un grand poisson?",
        options: ["Jonas", "Ésaïe", "Jérémie", "Michée"],
        correctAnswer: 0,
        explanation: "Jonas a été avalé par un grand poisson pendant 3 jours.",
      },
      {
        id: "3-3",
        question: "Quel prophète a vu une vision de roues dans le ciel?",
        options: ["Ézéchiel", "Daniel", "Ésaïe", "Jérémie"],
        correctAnswer: 0,
        explanation: "Ézéchiel a vu une vision de roues enflammées.",
      },
      {
        id: "3-4",
        question: "Quel prophète a pleuré sur Jérusalem?",
        options: ["Ésaïe", "Jérémie", "Ézéchiel", "Osée"],
        correctAnswer: 1,
        explanation: "Jérémie, appelé 'le prophète qui pleure', a pleuré sur Jérusalem.",
      },
      {
        id: "3-5",
        question: "Quel prophète a prophétisé la destruction du temple?",
        options: ["Ésaïe", "Jérémie", "Ézéchiel", "Daniel"],
        correctAnswer: 1,
        explanation: "Jérémie a prophétisé la destruction du temple de Jérusalem.",
      },
      {
        id: "3-6",
        question: "Quel prophète a reçu un appel divin dans le temple?",
        options: ["Ésaïe", "Jérémie", "Ézéchiel", "Osée"],
        correctAnswer: 0,
        explanation: "Ésaïe a reçu son appel prophétique dans le temple.",
      },
      {
        id: "3-7",
        question: "Quel prophète a prophétisé 70 semaines?",
        options: ["Ézéchiel", "Daniel", "Ésaïe", "Jérémie"],
        correctAnswer: 1,
        explanation: "Daniel a prophétisé les 70 semaines.",
      },
      {
        id: "3-8",
        question: "Quel prophète a vu le Seigneur sur un trône?",
        options: ["Jérémie", "Ésaïe", "Ézéchiel", "Osée"],
        correctAnswer: 1,
        explanation: "Ésaïe a vu le Seigneur assis sur un trône élevé.",
      },
      {
        id: "3-9",
        question: "Quel prophète a prophétisé la naissance du Messie à Bethléem?",
        options: ["Ésaïe", "Michée", "Jérémie", "Ézéchiel"],
        correctAnswer: 1,
        explanation: "Michée a prophétisé que le Messie naîtrait à Bethléem.",
      },
      {
        id: "3-10",
        question: "Quel prophète a prophétisé les souffrances du Messie?",
        options: ["Jérémie", "Ésaïe", "Ézéchiel", "Osée"],
        correctAnswer: 1,
        explanation: "Ésaïe a prophétisé les souffrances du Messie (Ésaïe 53).",
      },
    ],
  },
  {
    id: "4",
    title: "Psaumes",
    description: "Explorez les Psaumes de David",
    icon: "🎵",
    difficulty: "facile",
    questions: [
      {
        id: "4-1",
        question: "Combien de Psaumes contient le livre des Psaumes?",
        options: ["100 psaumes", "120 psaumes", "150 psaumes", "200 psaumes"],
        correctAnswer: 2,
        explanation: "Le livre des Psaumes contient 150 psaumes.",
      },
      {
        id: "4-2",
        question: "Quel est le Psaume le plus connu?",
        options: ["Psaume 1", "Psaume 23", "Psaume 100", "Psaume 150"],
        correctAnswer: 1,
        explanation: "Le Psaume 23 est le plus connu: 'L'Éternel est mon berger'.",
      },
      {
        id: "4-3",
        question: "Qui a écrit la plupart des Psaumes?",
        options: ["Salomon", "David", "Moïse", "Josué"],
        correctAnswer: 1,
        explanation: "David a écrit la plupart des Psaumes.",
      },
      {
        id: "4-4",
        question: "Quel Psaume parle de la création du monde?",
        options: ["Psaume 8", "Psaume 19", "Psaume 24", "Psaume 33"],
        correctAnswer: 1,
        explanation: "Le Psaume 19 parle de la création et de la gloire de Dieu.",
      },
      {
        id: "4-5",
        question: "Quel Psaume est un hymne de louange?",
        options: ["Psaume 42", "Psaume 100", "Psaume 88", "Psaume 13"],
        correctAnswer: 1,
        explanation: "Le Psaume 100 est un hymne de louange et d'action de grâces.",
      },
      {
        id: "4-6",
        question: "Quel Psaume exprime la confiance en Dieu?",
        options: ["Psaume 23", "Psaume 42", "Psaume 88", "Psaume 137"],
        correctAnswer: 0,
        explanation: "Le Psaume 23 exprime la confiance en Dieu comme berger.",
      },
      {
        id: "4-7",
        question: "Quel Psaume parle de la repentance?",
        options: ["Psaume 32", "Psaume 51", "Psaume 130", "Tous les trois"],
        correctAnswer: 3,
        explanation: "Les Psaumes 32, 51 et 130 parlent tous de repentance.",
      },
      {
        id: "4-8",
        question: "Quel est le Psaume le plus court?",
        options: ["Psaume 100", "Psaume 117", "Psaume 119", "Psaume 150"],
        correctAnswer: 1,
        explanation: "Le Psaume 117 est le plus court avec seulement 2 versets.",
      },
      {
        id: "4-9",
        question: "Quel Psaume est le plus long?",
        options: ["Psaume 100", "Psaume 119", "Psaume 150", "Psaume 89"],
        correctAnswer: 1,
        explanation: "Le Psaume 119 est le plus long avec 176 versets.",
      },
      {
        id: "4-10",
        question: "Quel Psaume parle de la justice de Dieu?",
        options: ["Psaume 7", "Psaume 37", "Psaume 89", "Psaume 97"],
        correctAnswer: 3,
        explanation: "Le Psaume 97 parle de la justice et de la majesté de Dieu.",
      },
    ],
  },
  {
    id: "5",
    title: "Miracles",
    description: "Testez vos connaissances sur les miracles bibliques",
    icon: "✨",
    difficulty: "moyen",
    questions: [
      {
        id: "5-1",
        question: "Quel était le premier miracle de Jésus?",
        options: ["Guérir un lépreux", "Transformer l'eau en vin", "Marcher sur l'eau", "Ressusciter Lazare"],
        correctAnswer: 1,
        explanation: "Le premier miracle de Jésus était de transformer l'eau en vin à Cana.",
      },
      {
        id: "5-2",
        question: "Combien de pains Jésus a-t-il multiplié pour nourrir 5000 personnes?",
        options: ["3 pains", "5 pains", "7 pains", "10 pains"],
        correctAnswer: 1,
        explanation: "Jésus a multiplié 5 pains et 2 poissons.",
      },
      {
        id: "5-3",
        question: "Quel miracle Jésus a-t-il accompli sur la mer?",
        options: ["Marcher sur l'eau", "Calmer la tempête", "Transformer l'eau", "Les deux premiers"],
        correctAnswer: 3,
        explanation: "Jésus a marché sur l'eau et a calmé la tempête.",
      },
      {
        id: "5-4",
        question: "Quel homme Jésus a-t-il ressuscité après 4 jours?",
        options: ["Pierre", "Lazare", "Jean", "Thomas"],
        correctAnswer: 1,
        explanation: "Jésus a ressuscité Lazare qui était mort depuis 4 jours.",
      },
      {
        id: "5-5",
        question: "Quel aveugle Jésus a-t-il guéri à Jéricho?",
        options: ["Bartimée", "Zacchée", "Simon", "Matthieu"],
        correctAnswer: 0,
        explanation: "Jésus a guéri Bartimée, un aveugle à Jéricho.",
      },
      {
        id: "5-6",
        question: "Quel miracle Élisée a-t-il accompli avec de l'huile?",
        options: ["Multiplier l'huile", "Guérir avec l'huile", "Transformer l'huile", "Purifier l'huile"],
        correctAnswer: 0,
        explanation: "Élisée a multiplié l'huile d'une veuve.",
      },
      {
        id: "5-7",
        question: "Quel miracle Élie a-t-il accompli avec le feu?",
        options: ["Faire tomber le feu du ciel", "Arrêter le feu", "Transformer le feu", "Purifier le feu"],
        correctAnswer: 0,
        explanation: "Élie a fait tomber le feu du ciel sur le Mont Carmel.",
      },
      {
        id: "5-8",
        question: "Quel miracle Moïse a-t-il accompli avec son bâton?",
        options: ["Transformer l'eau en sang", "Diviser la mer", "Faire tomber la manne", "Tous les trois"],
        correctAnswer: 3,
        explanation: "Moïse a accompli plusieurs miracles avec son bâton.",
      },
      {
        id: "5-9",
        question: "Quel miracle Josué a-t-il accompli à Jéricho?",
        options: ["Arrêter le soleil", "Faire tomber les murs", "Diviser le Jourdain", "Faire tomber la manne"],
        correctAnswer: 1,
        explanation: "Josué a fait tomber les murs de Jéricho.",
      },
      {
        id: "5-10",
        question: "Quel miracle Samson a-t-il accompli?",
        options: ["Guérir les malades", "Déplacer les montagnes", "Détruire le temple", "Marcher sur l'eau"],
        correctAnswer: 2,
        explanation: "Samson a détruit le temple des Philistins.",
      },
    ],
  },
  {
    id: "6",
    title: "Paraboles",
    description: "Explorez les paraboles de Jésus",
    icon: "📖",
    difficulty: "moyen",
    questions: [
      {
        id: "6-1",
        question: "Quel était le sujet de la parabole du semeur?",
        options: ["L'amour", "La foi", "La Parole de Dieu", "L'espérance"],
        correctAnswer: 2,
        explanation: "La parabole du semeur parle de la Parole de Dieu semée dans les cœurs.",
      },
      {
        id: "6-2",
        question: "Quel était le sujet de la parabole du fils prodigue?",
        options: ["La repentance", "L'amour du père", "Le pardon", "Tous les trois"],
        correctAnswer: 3,
        explanation: "La parabole du fils prodigue parle de repentance, d'amour et de pardon.",
      },
      {
        id: "6-3",
        question: "Quel était le sujet de la parabole du bon Samaritain?",
        options: ["L'amour du prochain", "La miséricorde", "La charité", "Tous les trois"],
        correctAnswer: 3,
        explanation: "La parabole du bon Samaritain parle d'amour, de miséricorde et de charité.",
      },
      {
        id: "6-4",
        question: "Quel était le sujet de la parabole du trésor caché?",
        options: ["La richesse", "Le Royaume de Dieu", "L'avarice", "La générosité"],
        correctAnswer: 1,
        explanation: "La parabole du trésor caché parle du Royaume de Dieu.",
      },
      {
        id: "6-5",
        question: "Quel était le sujet de la parabole de la graine de moutarde?",
        options: ["La croissance", "Le Royaume de Dieu", "La foi", "Tous les trois"],
        correctAnswer: 3,
        explanation: "La parabole de la graine de moutarde parle de croissance, du Royaume et de la foi.",
      },
      {
        id: "6-6",
        question: "Quel était le sujet de la parabole des dix vierges?",
        options: ["La vigilance", "La préparation", "Le retour de Jésus", "Tous les trois"],
        correctAnswer: 3,
        explanation: "La parabole des dix vierges parle de vigilance, préparation et du retour de Jésus.",
      },
      {
        id: "6-7",
        question: "Quel était le sujet de la parabole des talents?",
        options: ["La responsabilité", "L'intendance", "L'utilisation des dons", "Tous les trois"],
        correctAnswer: 3,
        explanation: "La parabole des talents parle de responsabilité, intendance et utilisation des dons.",
      },
      {
        id: "6-8",
        question: "Quel était le sujet de la parabole du levain?",
        options: ["La croissance", "L'influence", "Le Royaume de Dieu", "Tous les trois"],
        correctAnswer: 3,
        explanation: "La parabole du levain parle de croissance, influence et du Royaume de Dieu.",
      },
      {
        id: "6-9",
        question: "Quel était le sujet de la parabole du filet?",
        options: ["La pêche", "Le jugement", "Le Royaume de Dieu", "Tous les trois"],
        correctAnswer: 2,
        explanation: "La parabole du filet parle du Royaume de Dieu et du jugement.",
      },
      {
        id: "6-10",
        question: "Quel était le sujet de la parabole de la brebis perdue?",
        options: ["L'amour", "La recherche", "Le pardon", "Tous les trois"],
        correctAnswer: 3,
        explanation: "La parabole de la brebis perdue parle d'amour, de recherche et de pardon.",
      },
    ],
  },
  {
    id: "7",
    title: "Apôtres",
    description: "Testez vos connaissances sur les apôtres",
    icon: "👥",
    difficulty: "moyen",
    questions: [
      {
        id: "7-1",
        question: "Quel était le vrai nom de Pierre?",
        options: ["Siméon", "Simon", "Saul", "Jean"],
        correctAnswer: 1,
        explanation: "Pierre s'appelait Simon avant que Jésus le renomme Pierre.",
      },
      {
        id: "7-2",
        question: "Quel apôtre était un collecteur d'impôts?",
        options: ["Pierre", "Jean", "Matthieu", "André"],
        correctAnswer: 2,
        explanation: "Matthieu était un collecteur d'impôts avant de devenir apôtre.",
      },
      {
        id: "7-3",
        question: "Quel apôtre a écrit le plus de livres du Nouveau Testament?",
        options: ["Pierre", "Jean", "Paul", "Jacques"],
        correctAnswer: 2,
        explanation: "Paul a écrit 13 ou 14 livres du Nouveau Testament.",
      },
      {
        id: "7-4",
        question: "Quel apôtre a douté de la résurrection de Jésus?",
        options: ["Pierre", "Thomas", "Jean", "André"],
        correctAnswer: 1,
        explanation: "Thomas a douté jusqu'à ce qu'il voie Jésus ressuscité.",
      },
      {
        id: "7-5",
        question: "Quel apôtre était le frère de Pierre?",
        options: ["Jean", "André", "Jacques", "Matthieu"],
        correctAnswer: 1,
        explanation: "André était le frère de Pierre.",
      },
      {
        id: "7-6",
        question: "Quel apôtre a écrit l'Apocalypse?",
        options: ["Pierre", "Jean", "Paul", "Jacques"],
        correctAnswer: 1,
        explanation: "Jean a écrit l'Apocalypse.",
      },
      {
        id: "7-7",
        question: "Quel apôtre a été crucifié la tête en bas?",
        options: ["Pierre", "Paul", "Jean", "Jacques"],
        correctAnswer: 0,
        explanation: "Pierre a été crucifié la tête en bas selon la tradition.",
      },
      {
        id: "7-8",
        question: "Quel apôtre a été décapité?",
        options: ["Pierre", "Paul", "Jean", "Jacques"],
        correctAnswer: 1,
        explanation: "Paul a été décapité à Rome.",
      },
      {
        id: "7-9",
        question: "Quel apôtre était un zélote?",
        options: ["Simon", "Judas", "Barthélemy", "Matthieu"],
        correctAnswer: 0,
        explanation: "Simon le Zélote était un apôtre.",
      },
      {
        id: "7-10",
        question: "Quel apôtre a remplacé Judas?",
        options: ["Matthias", "Barnabas", "Silas", "Timothée"],
        correctAnswer: 0,
        explanation: "Matthias a été choisi pour remplacer Judas.",
      },
    ],
  },
  {
    id: "8",
    title: "Création",
    description: "Explorez l'histoire de la création",
    icon: "🌍",
    difficulty: "facile",
    questions: [
      {
        id: "8-1",
        question: "En combien de jours Dieu a-t-il créé le monde?",
        options: ["5 jours", "6 jours", "7 jours", "8 jours"],
        correctAnswer: 1,
        explanation: "Dieu a créé le monde en 6 jours.",
      },
      {
        id: "8-2",
        question: "Quel jour Dieu a-t-il créé la lumière?",
        options: ["Premier jour", "Deuxième jour", "Troisième jour", "Quatrième jour"],
        correctAnswer: 0,
        explanation: "Dieu a créé la lumière le premier jour.",
      },
      {
        id: "8-3",
        question: "Quel jour Dieu a-t-il créé les animaux?",
        options: ["Quatrième jour", "Cinquième jour", "Sixième jour", "Septième jour"],
        correctAnswer: 2,
        explanation: "Dieu a créé les animaux le sixième jour.",
      },
      {
        id: "8-4",
        question: "Quel jour Dieu a-t-il créé l'homme?",
        options: ["Quatrième jour", "Cinquième jour", "Sixième jour", "Septième jour"],
        correctAnswer: 2,
        explanation: "Dieu a créé l'homme le sixième jour.",
      },
      {
        id: "8-5",
        question: "Quel jour Dieu s'est-il reposé?",
        options: ["Cinquième jour", "Sixième jour", "Septième jour", "Huitième jour"],
        correctAnswer: 2,
        explanation: "Dieu s'est reposé le septième jour.",
      },
      {
        id: "8-6",
        question: "Quel jour Dieu a-t-il créé le ciel et la terre?",
        options: ["Premier jour", "Deuxième jour", "Troisième jour", "Quatrième jour"],
        correctAnswer: 0,
        explanation: "Dieu a créé le ciel et la terre le premier jour.",
      },
      {
        id: "8-7",
        question: "Quel jour Dieu a-t-il créé les plantes?",
        options: ["Deuxième jour", "Troisième jour", "Quatrième jour", "Cinquième jour"],
        correctAnswer: 1,
        explanation: "Dieu a créé les plantes le troisième jour.",
      },
      {
        id: "8-8",
        question: "Quel jour Dieu a-t-il créé le soleil et la lune?",
        options: ["Deuxième jour", "Troisième jour", "Quatrième jour", "Cinquième jour"],
        correctAnswer: 2,
        explanation: "Dieu a créé le soleil et la lune le quatrième jour.",
      },
      {
        id: "8-9",
        question: "Quel jour Dieu a-t-il créé les poissons et les oiseaux?",
        options: ["Troisième jour", "Quatrième jour", "Cinquième jour", "Sixième jour"],
        correctAnswer: 2,
        explanation: "Dieu a créé les poissons et les oiseaux le cinquième jour.",
      },
      {
        id: "8-10",
        question: "À l'image de qui Dieu a-t-il créé l'homme?",
        options: ["À l'image des anges", "À l'image de Dieu", "À l'image de la nature", "À l'image des animaux"],
        correctAnswer: 1,
        explanation: "Dieu a créé l'homme à son image.",
      },
    ],
  },
  {
    id: "9",
    title: "Noël",
    description: "Testez vos connaissances sur la naissance de Jésus",
    icon: "🎄",
    difficulty: "facile",
    questions: [
      {
        id: "9-1",
        question: "En quel mois Jésus est-il né selon la tradition?",
        options: ["Octobre", "Novembre", "Décembre", "Janvier"],
        correctAnswer: 2,
        explanation: "Selon la tradition, Jésus est né en décembre.",
      },
      {
        id: "9-2",
        question: "Dans quel lieu Jésus est-il né?",
        options: ["Nazareth", "Jérusalem", "Bethléem", "Égypte"],
        correctAnswer: 2,
        explanation: "Jésus est né à Bethléem.",
      },
      {
        id: "9-3",
        question: "Quel animal a été le premier à voir Jésus?",
        options: ["Un chameau", "Un âne", "Une brebis", "Un boeuf"],
        correctAnswer: 3,
        explanation: "Un boeuf et un âne étaient à la crèche.",
      },
      {
        id: "9-4",
        question: "Qui a annoncé la naissance de Jésus aux bergers?",
        options: ["Un prophète", "Un ange", "Une étoile", "Un roi"],
        correctAnswer: 1,
        explanation: "Un ange a annoncé la naissance de Jésus aux bergers.",
      },
      {
        id: "9-5",
        question: "Combien de mages ont visité Jésus?",
        options: ["Deux mages", "Trois mages", "Quatre mages", "Cinq mages"],
        correctAnswer: 1,
        explanation: "Trois mages ont visité Jésus.",
      },
      {
        id: "9-6",
        question: "Quel signe céleste a guidé les mages?",
        options: ["Une comète", "Une étoile", "Une lune", "Une aurore"],
        correctAnswer: 1,
        explanation: "Une étoile a guidé les mages.",
      },
      {
        id: "9-7",
        question: "Quels cadeaux les mages ont-ils apportés?",
        options: ["Or, argent, bronze", "Or, encens, myrrhe", "Or, argent, myrrhe", "Encens, myrrhe, bronze"],
        correctAnswer: 1,
        explanation: "Les mages ont apporté de l'or, de l'encens et de la myrrhe.",
      },
      {
        id: "9-8",
        question: "Quel roi a ordonné la mort des enfants?",
        options: ["Hérode", "Pilate", "Tibère", "Caïphe"],
        correctAnswer: 0,
        explanation: "Le roi Hérode a ordonné la mort des enfants.",
      },
      {
        id: "9-9",
        question: "En quel pays Jésus a-t-il fui pour échapper à Hérode?",
        options: ["Syrie", "Égypte", "Arabie", "Perse"],
        correctAnswer: 1,
        explanation: "Jésus a fui en Égypte.",
      },
      {
        id: "9-10",
        question: "Quel prophète a prophétisé la naissance de Jésus à Bethléem?",
        options: ["Ésaïe", "Jérémie", "Michée", "Ézéchiel"],
        correctAnswer: 2,
        explanation: "Michée a prophétisé que le Messie naîtrait à Bethléem.",
      },
    ],
  },
  {
    id: "10",
    title: "Pâques",
    description: "Explorez l'histoire de la résurrection",
    icon: "🐣",
    difficulty: "moyen",
    questions: [
      {
        id: "10-1",
        question: "Quel jour Jésus a-t-il été crucifié?",
        options: ["Jeudi", "Vendredi", "Samedi", "Dimanche"],
        correctAnswer: 1,
        explanation: "Jésus a été crucifié un vendredi.",
      },
      {
        id: "10-2",
        question: "Quel jour Jésus a-t-il ressuscité?",
        options: ["Samedi", "Dimanche", "Lundi", "Mardi"],
        correctAnswer: 1,
        explanation: "Jésus a ressuscité le dimanche.",
      },
      {
        id: "10-3",
        question: "Combien de jours Jésus est-il resté dans le tombeau?",
        options: ["1 jour", "2 jours", "3 jours", "4 jours"],
        correctAnswer: 2,
        explanation: "Jésus est resté 3 jours dans le tombeau.",
      },
      {
        id: "10-4",
        question: "Qui a découvert le tombeau vide en premier?",
        options: ["Pierre", "Jean", "Marie-Madeleine", "Les apôtres"],
        correctAnswer: 2,
        explanation: "Marie-Madeleine a découvert le tombeau vide en premier.",
      },
      {
        id: "10-5",
        question: "Quel était le motif de la crucifixion de Jésus?",
        options: ["Blasphème", "Sédition", "Tous les deux", "Aucun des deux"],
        correctAnswer: 2,
        explanation: "Jésus a été accusé de blasphème et de sédition.",
      },
      {
        id: "10-6",
        question: "Qui a ordonné la crucifixion de Jésus?",
        options: ["Hérode", "Caïphe", "Pilate", "Les Romains"],
        correctAnswer: 2,
        explanation: "Ponce Pilate a ordonné la crucifixion de Jésus.",
      },
      {
        id: "10-7",
        question: "Quel était le lieu de la crucifixion?",
        options: ["Golgotha", "Gethsémani", "Béthanie", "Jérusalem"],
        correctAnswer: 0,
        explanation: "Jésus a été crucifié au Golgotha.",
      },
      {
        id: "10-8",
        question: "Combien de personnes ont été crucifiées avec Jésus?",
        options: ["Un", "Deux", "Trois", "Quatre"],
        correctAnswer: 1,
        explanation: "Deux criminels ont été crucifiés avec Jésus.",
      },
      {
        id: "10-9",
        question: "Quel apôtre a nié Jésus trois fois?",
        options: ["Jean", "Pierre", "Thomas", "André"],
        correctAnswer: 1,
        explanation: "Pierre a nié Jésus trois fois.",
      },
      {
        id: "10-10",
        question: "Quel était le signe de la résurrection de Jésus?",
        options: ["La pierre roulée", "Le tombeau vide", "Les anges", "Tous les trois"],
        correctAnswer: 3,
        explanation: "La pierre roulée, le tombeau vide et les anges étaient des signes de la résurrection.",
      },
    ],
  },
];
